[package]
name = "occurrence"
version = "0.1.0"
authors = ["Ziyang Li <liby99@seas.upenn.edu>"]
edition = "2018"

[dependencies]
analyzer-core = { path = "../core" }
clap = "3.0.0-beta.1"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
petgraph = "0.5"
