[package]
name = "new_analyzer"
version = "0.1.0"
authors = ["Ziyang Li <liby99@seas.upenn.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
petgraph = "0.5"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "llvm10-0" }
either = "1.5"
clap = "3.0.0-beta.1"